#!/bin/bash
# GitHub Fine-grained PAT Setup Script

echo "🚀 GitHub Fine-grained PAT Authentication Setup"
echo "==============================================="
echo ""
echo "To resolve the 401 Unauthorized error, you need a GitHub Fine-grained Personal Access Token."
echo ""
echo "📋 Steps to create a Fine-grained PAT:"
echo "1. Go to: https://github.com/settings/personal-access-tokens/fine-grained"
echo "2. Click 'Generate new token'"
echo "3. Configure the token:"
echo "   • Token name: 'Portfolio Website API'"
echo "   • Expiration: 1 year (recommended)"
echo "   • Resource owner: Select your username (Night-Shift101)"
echo "   • Repository access: 'Selected repositories'"
echo "   • Select repositories: Choose your public repositories"
echo ""
echo "4. Set Repository permissions:"
echo "   ✅ Contents: Read (to read repository files)"
echo "   ✅ Metadata: Read (to read repository metadata)"
echo "   ✅ Pull requests: Read (to read PR information)"
echo "   ✅ Issues: Read (to read issue information)"
echo "   ✅ Actions: Read (to read workflow information)"
echo ""
echo "5. Set Account permissions (optional but recommended):"
echo "   ✅ Git SSH keys: Read"
echo "   ✅ GPG keys: Read"
echo "   ✅ Profile: Read"
echo ""
echo "6. Click 'Generate token'"
echo "7. Copy the token (starts with 'github_pat_')"
echo ""
echo "🔧 Setup instructions:"
echo "1. Create a file called '.env.local' in your project root"
echo "2. Add this line (replace with your actual token):"
echo "   GITHUB_TOKEN=github_pat_your_token_here"
echo "3. Restart your development server: npm run dev"
echo ""
echo "⚠️  IMPORTANT SECURITY NOTES:"
echo "• Never commit your .env.local file to Git!"
echo "• Fine-grained PATs have stricter permissions than classic tokens"
echo "• Ensure your token has access to the repositories you want to query"
echo ""
echo "✨ Benefits of Fine-grained PATs:"
echo "• More granular security control"
echo "• Repository-specific permissions"
echo "• Better audit logging"
echo "• Higher rate limits (5000 requests/hour vs 60)"
echo "• Access to detailed repository data"
echo ""
echo "🔍 Troubleshooting:"
echo "If you still get 401 errors after setup:"
echo "1. Check that your token hasn't expired"
echo "2. Verify repository permissions in token settings"
echo "3. Ensure the token has 'Contents' and 'Metadata' read permissions"
echo "4. Check that you've selected the correct repositories"
echo ""
echo "Need help? Check the GitHub documentation:"
echo "https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-fine-grained-personal-access-token"
